# Generated by Django 5.2.11 on 2026-03-02 12:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(choices=[(0, '07:00 – 10:00'), (1, '10:00 – 13:00'), (2, '13:00 – 16:00'), (3, '16:00 – 19:00'), (4, '19:00 – 22:00')], help_text='The time-slot index (0-4).', unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price in EUR for this slot.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Slot Pricing',
                'verbose_name_plural': 'Slot Pricings',
                'ordering': ['slot_number'],
                'indexes': [models.Index(fields=['slot_number'], name='idx_slotpricing_slot')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the booking.')),
                ('booking_type', models.CharField(choices=[('slot', 'Single Slot (3 hours)'), ('full_day', 'Full Day (07:00 – 22:00)')], default='slot', max_length=10)),
                ('slot_number', models.IntegerField(blank=True, choices=[(0, '07:00 – 10:00'), (1, '10:00 – 13:00'), (2, '13:00 – 16:00'), (3, '16:00 – 19:00'), (4, '19:00 – 22:00')], help_text='Required for single-slot bookings (0-4). Null for full-day.', null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost at time of booking.', max_digits=8)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['date', 'slot_number'],
                'indexes': [models.Index(fields=['user', 'is_cancelled'], name='idx_booking_user_active'), models.Index(fields=['date'], name='idx_booking_date'), models.Index(fields=['date', 'slot_number'], name='idx_booking_date_slot'), models.Index(fields=['user', 'date'], name='idx_booking_user_date'), models.Index(fields=['is_cancelled'], name='idx_booking_cancelled'), models.Index(fields=['created_at'], name='idx_booking_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('date', 'slot_number'), name='unique_active_date_slot')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(help_text='Apartment number (e.g. A12, B3, 101).', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['apartment_number'], name='idx_profile_apartment')],
            },
        ),
    ]
